# model_config.yaml

# Example model config for GLM or XGBoost

model_type: "XGBoost"
target_variable: "reserve_adequacy_score"
features:
  - paid_to_incurred_ratio
  - claim_duration
  - policy_limit_ratio
parameters:
  learning_rate: 0.1
  max_depth: 5
